services:
  caddy:
    image: caddy:2.11
    restart: unless-stopped
    ports:
      - "7999:80"
    volumes:
      - ./conf:/etc/caddy
      - ./docs/html:/srv
      - caddy_data:/data

volumes:
  caddy_data:

