services:
  caddy:
    image: caddy:2.11
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - $PWD/conf:/etc/caddy
      - $PWD/docs/html:/srv
      - caddy_data:/data

volumes:
  caddy_data:

